In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [4]:
s = pd.Series(np.random.randn(5), index=['a','b','c','d','e'])
s

a    0.572967
b    0.491866
c    0.077208
d    0.972390
e    1.056334
dtype: float64

In [6]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [8]:
pd.Series(np.random.randn(5))

0   -0.191709
1   -0.587586
2   -0.453067
3    0.736959
4   -0.016383
dtype: float64

In [15]:
d = {'b':1,'a':3,'c':2}

In [16]:
pd.Series(d)

a    3
b    1
c    2
dtype: int64

In [18]:
d = {'a':1.,'c':2.,'b':0.}

In [20]:
pd.Series(d)

a    1.0
b    0.0
c    2.0
dtype: float64

In [22]:
pd.Series(d,index=['b','c','a','d'])

b    0.0
c    2.0
a    1.0
d    NaN
dtype: float64

In [23]:
pd.Series(5,index=['a','b','c','d','e'])

a    5
b    5
c    5
d    5
e    5
dtype: int64

In [24]:
s[0]

0.5729667780281319

In [25]:
s[:3]

a    0.572967
b    0.491866
c    0.077208
dtype: float64

In [26]:
s[s>s.median()]

d    0.972390
e    1.056334
dtype: float64

In [27]:
s[[4,3,1]]

e    1.056334
d    0.972390
b    0.491866
dtype: float64

In [28]:
np.exp(s)

a    1.773521
b    1.635366
c    1.080267
d    2.644256
e    2.875808
dtype: float64

In [29]:
s['a']

0.5729667780281319

In [30]:
'e' in s

True

In [33]:
s.get('d')


0.9723898816702375

In [35]:
s.get('f',np.nan)

nan

In [36]:
d = {'one':pd.Series([1.,2.,3.], index=['a','b','c']),
     'two':pd.Series([1.,2.,3.,4.], index=['a','b','c','d']),
     'three':pd.Series([1.,2.,3.,4.,5.], index=['a','b','c',
                                               'd','f'])}

In [37]:
df = pd.DataFrame(d)

In [38]:
df

one  three  two
a  1.0    1.0  1.0
b  2.0    2.0  2.0
c  3.0    3.0  3.0
d  NaN    4.0  4.0
f  NaN    5.0  NaN

In [39]:
pd.DataFrame(d, index=['d','b','a'])

one  three  two
d  NaN    4.0  4.0
b  2.0    2.0  2.0
a  1.0    1.0  1.0

In [40]:
pd.DataFrame(d, index=['d','b','a'], columns=['two','three'])

two  three
d  4.0    4.0
b  2.0    2.0
a  1.0    1.0

In [41]:
df.index

Index(['a', 'b', 'c', 'd', 'f'], dtype='object')

In [42]:
df.columns

Index(['one', 'three', 'two'], dtype='object')

In [45]:
d = {'one':[1.,2.,3.,4.],
    'two':[5.,6.,7.,8.]}

In [47]:
pd.DataFrame(d)

one  two
0  1.0  5.0
1  2.0  6.0
2  3.0  7.0
3  4.0  8.0

In [48]:
pd.DataFrame(d, index=['a','b','c','d'])

one  two
a  1.0  5.0
b  2.0  6.0
c  3.0  7.0
d  4.0  8.0

In [51]:
data = np.zeros((2,),dtype=[('A','i4'),('B','f4'),('C','a10')])

In [54]:
data[:] = [(1,2.,'Hello'),(2,3.,'World')]

In [56]:
pd.DataFrame(data, index=['First','Second'])

A    B         C
First   1  2.0  b'Hello'
Second  2  3.0  b'World'

In [57]:
data2 = [{'a':1,'b':2},{'c':4.,'d':5.}]

In [60]:
pd.DataFrame(data2)

a    b    c    d
0  1.0  2.0  NaN  NaN
1  NaN  NaN  4.0  5.0

In [62]:
pd.DataFrame(data2, index=['First','Second'])

a    b    c    d
First   1.0  2.0  NaN  NaN
Second  NaN  NaN  4.0  5.0

In [64]:
pd.DataFrame(data2, columns=['a','b'])

a    b
0  1.0  2.0
1  NaN  NaN

In [68]:
pd.DataFrame.from_dict(dict([('A',[1,23,4]),('B',[2, 35, 5])]))

A   B
0   1   2
1  23  35
2   4   5

In [69]:
pd.DataFrame.from_dict(dict([('A',[1,2,3]),('B',[4,5,6])]),
                      orient='index',columns=['one','two','three'])

one  two  three
A    1    2      3
B    4    5      6

In [70]:
data

array([(1, 2., b'Hello'), (2, 3., b'World')],
      dtype=[('A', '<i4'), ('B', '<f4'), ('C', 'S10')])

In [72]:
df.loc['b']

one      2.0
three    2.0
two      2.0
Name: b, dtype: float64

In [73]:
df.iloc[2]

one      3.0
three    3.0
two      3.0
Name: c, dtype: float64

In [74]:
df

one  three  two
a  1.0    1.0  1.0
b  2.0    2.0  2.0
c  3.0    3.0  3.0
d  NaN    4.0  4.0
f  NaN    5.0  NaN

In [76]:
 df.loc['a']

one      1.0
three    1.0
two      1.0
Name: a, dtype: float64

In [77]:
df['one']

a    1.0
b    2.0
c    3.0
d    NaN
f    NaN
Name: one, dtype: float64

In [79]:
df.iloc[0]

one      1.0
three    1.0
two      1.0
Name: a, dtype: float64

In [81]:
df[:2]

one  three  two
a  1.0    1.0  1.0
b  2.0    2.0  2.0

In [82]:
df.describe()

one     three       two
count  3.0  5.000000  4.000000
mean   2.0  3.000000  2.500000
std    1.0  1.581139  1.290994
min    1.0  1.000000  1.000000
25%    1.5  2.000000  1.750000
50%    2.0  3.000000  2.500000
75%    2.5  4.000000  3.250000
max    3.0  5.000000  4.000000

In [87]:
from sklearn import preprocessing
import numpy as np
    
x = np.array([[1.,-1,2.],
             [2.,0.,0],
             [0.,1.,-1]])

In [88]:
x

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [97]:
scaler = preprocessing.StandardScaler().fit(x)

In [103]:
scaler.mean_

array([1.        , 0.        , 0.33333333])

In [108]:
scaler.scale_

array([0.81649658, 0.81649658, 1.24721913])

In [109]:
(2 - 1) / scaler.scale_[0]

1.224744871391589

In [101]:
scaler.transform(x)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [102]:
new_x = [[-1.,1.,0.]]
scaler.transform(new_x)

array([[-2.44948974,  1.22474487, -0.26726124]])

In [118]:
y = pd.Series([1],[2],[3],[4],[5],[6],[7],[8])

TypeError: __init__() takes from 1 to 7 positional arguments but 9 were given

In [111]:
y

[1, 2, 3, 4, 5, 6, 7, 8]